### ISSUE TITLE
Game now up on nimgame.online

### ISSUE THREAD

**Issue by JohnAD** [ftsf/ld38-smalltrek#1]
Just FYI: this game is now up on https://nimgame.online/

Ironically, I've had a hard time finding sample nim games to spotlight. Thanks for making this one available.

BTW, the JS code I'm using is on itch.io. I could not actually compile the game; I suspect it was version problems (both the version of nim needed and the version of the needed libraries.) If you get a chance, you might want to add a `smalltrek.nimble` file to the repo with the details.

**Comment by clort81** [comment]
Good game!
